apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tensorizer-benchmark-nvme
spec:
  storageClassName: shared-nvme-las1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi