apiVersion: batch/v1
kind: Job
metadata:
  name: tensorizer-benchmark-read-size
spec:
  parallelism: 10
  completions: 100
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: ethernet.coreweave.cloud/speed
                operator: In
                values:
                   #- 10G
                   - 40G
                   - 100G
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - LGA1
                - LAS1
                - ORD1
      containers:
        - name: benchmark
          image: ghcr.io/coreweave/tensorizer:benchmark-fe3982d
          imagePullPolicy: IfNotPresent
          command: [ "/bin/bash" ]
          args: [ "-c", "redis-server --daemonize yes >/dev/null & python /app/benchmark.py" ]
          #--redis redis://redis-master:6379" ]
          resources:
            requests:
              cpu: "8"
              memory: 64Gi
              nvidia.com/gpu: "1"
            limits:
              cpu: "8"
              memory: 64Gi
              nvidia.com/gpu: "1"
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              job-name: tensorizer-benchmark-read-size
      restartPolicy: OnFailure
