apiVersion: batch/v1
kind: Job
metadata:
  name: tensorizer-benchmark-read-size
spec:
  parallelism: 10
  completions: 100
  template:
    spec:
      containers:
        - name: benchmark
          image: ghcr.io/coreweave/tensorizer:benchmark-ddf4b3f
          imagePullPolicy: IfNotPresent
          command: [ "/bin/bash" ]
          args: [ "-c" "redis-server && python /app/benchmark.py" ]
          resources:
            requests:
              cpu: "8"
              memory: 64Gi
              nvidia.com/gpu: "1"
            limits:
              cpu: "8"
              memory: 64Gi
              nvidia.com/gpu: "1"
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              job-name: tensorizer-benchmark-read-size
      restartPolicy: OnFailure
